"""Init

Revision ID: e294fc38244a
Revises: 
Create Date: 2025-05-01 19:56:36.826322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e294fc38244a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cell_tower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radio', sa.Enum('GSM', 'CDMA', 'UMTS', 'WCDMA', 'LTE', 'NR', 'TETRA', name='radio_types'), nullable=False),
    sa.Column('mcc', sa.Integer(), nullable=False),
    sa.Column('mnc', sa.Integer(), nullable=False),
    sa.Column('lac', sa.Integer(), nullable=False),
    sa.Column('cellid', sa.Integer(), nullable=False),
    sa.Column('unused', sa.Integer(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('range', sa.Integer(), nullable=True),
    sa.Column('samples', sa.Integer(), nullable=True),
    sa.Column('changeable', sa.Integer(), nullable=True),
    sa.Column('created', sa.BigInteger(), nullable=True),
    sa.Column('updated', sa.BigInteger(), nullable=True),
    sa.Column('average_signal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cell_tower_mcc'), 'cell_tower', ['mcc'], unique=False)
    op.create_index(op.f('ix_cell_tower_mnc'), 'cell_tower', ['mnc'], unique=False)
    op.create_index('ix_coordinates', 'cell_tower', ['lat', 'lon'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_coordinates', table_name='cell_tower')
    op.drop_index(op.f('ix_cell_tower_mnc'), table_name='cell_tower')
    op.drop_index(op.f('ix_cell_tower_mcc'), table_name='cell_tower')
    op.drop_table('cell_tower')
    # ### end Alembic commands ###
