FROM node:lts

WORKDIR /app

COPY vue-frontend/package*.json ./
RUN npm install

# Copy the rest of the vue-frontend files
COPY vue-frontend/ .

EXPOSE 5173

CMD ["npm", "run", "dev",  "--", "--host"]
